using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using USoft.Globalization.Classes;
using USoft.Common.CommonFunction;
using USoft.DataAccess;
using USoft.Globalization;

namespace USoft.Modules.IT.Item
{
    public partial class ItemInAddEdit : USoft.Modules.PageBase
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            getUserInfo();
            LoadControl();

            if(!Page.IsPostBack)
            {
                //Binding
                //ControlBindingHelper.BindDataSetToCombo(ddlPIC, "- Select One -", "spGetMappingUsersToCombo 'State = 1'", "UserId", "UserName", null);
                ControlBindingHelper.BindDataSetToCombo(ddlBranch, "- Select One -", "spGetBranchToCombo ''", "BranchId", "BranchName", null);
                ControlBindingHelper.BindDataSetToCombo(ddlSupplier, "- Select One -", "spGetITSupplierToCombo 'State = ''IT'''", "SupplierCode", "SupplierName", null);
                
                if (this.state == "add")
                {
                    lblItemInCode.Text = "[Generated By System]";
                }
                else //edit
                {
                    LoadData();
                }

                ReceiveType();
            }
        }

        private void LoadControl()
        {
            ucHeaderPage.Text = cf.ToUpperFirstLetter(this.state) + " Item Receive";
            ucHeaderPage.CssClass = "divHeader1";
        }

        private void LoadData()
        {
            USoft.DataAccess.Entities.IT.Item info = new USoft.DataAccess.Entities.IT.Item();
            USoft.DataAccess.IT.Item da = new USoft.DataAccess.IT.Item();

            info.ItemInCode = editID;

            da.getItemInView(ref info);

            lblItemInCode.Text = info.ItemInCode;
            txtDateIn.Text = cf.DateFormatYYYYMMDD(info.Date);
            ddlReceiveType.SelectedValue = info.ReceiveType;
            ddlBranch.SelectedValue = info.BranchIdFrom.ToString();
            ddlSupplier.SelectedValue = info.SupplierCode.ToString();
            //ddlPIC.SelectedValue = info.PIC;
        }

        protected bool ProcessData(string state)
        {
            USoft.DataAccess.Entities.IT.Item info = new USoft.DataAccess.Entities.IT.Item();
            USoft.DataAccess.IT.Item da = new USoft.DataAccess.IT.Item();

            info.Date = Convert.ToDateTime(txtDateIn.Text);
            info.BranchIdFrom = (ddlReceiveType.SelectedValue == "1") ? Convert.ToInt32(ddlBranch.SelectedValue) : 0;
            info.SupplierCode = (ddlReceiveType.SelectedValue == "2") ? ddlSupplier.SelectedValue : "";
            //info.PIC = ddlPIC.SelectedValue;
            info.InputBy = Session["UserId"].ToString();

            if (state == "U")   // Update
            {
                info.ItemInCode = editID;
                lblMessage.Text = da.ItemIn_Update(info);
            }
            else // Add
            {
                lblMessage.Text = da.ItemIn_Insert(ref info);
                ReturnID = info.ItemInCode;
            }

            if (lblMessage.Text == "Process Success")   // Prevent Multiple Add
            {
                return true;
            }
            return false;
        }

        protected void imbSubmit_Click(object sender, ImageClickEventArgs e)
        {
            CekSessions.BlockUI(this.Page);

            if (this.state == "add")
            {
                if(ProcessData("A"))
                {
                    //imbSubmit.Visible = false;
                    Response.Redirect("ItemInDetail.aspx?validate=" + validate(0) + "&editID=" + ReturnID + "&msg=" + lblMessage.Text);
                }
            }
            else 
            { 
                ProcessData("U");
            }

            CekSessions.UnBlockUI(this.Page, ScriptManager1);
        }

        protected void RedirectPage()
        {
            if (from == "detail")
            {
                Response.Redirect("ItemInDetail.aspx?validate=" + validate(0) + "&editID=" + editID);
            }
            else
            {
                Response.Redirect("ItemIn.aspx?validate=" + validate(0));
            }
        }

        protected void imbBack_Click(object sender, ImageClickEventArgs e)
        {
            RedirectPage();
        }

        protected void ddlReceiveType_SelectedIndexChanged(object sender, EventArgs e)
        {
            ReceiveType();
            pnlReceiveType.Update();
        }

        private void ReceiveType()
        {
            ddlBranch.Visible = false;
            ddlSupplier.Visible = false;

            if (ddlReceiveType.SelectedValue == "1")
            {
                ddlBranch.Visible = true;
            }
            else if (ddlReceiveType.SelectedValue == "2")
            {
                ddlSupplier.Visible = true;
            }
        }

    }
}
