using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

using USoft.Globalization.Classes;
using USoft.Common.CommonFunction;
using USoft.DataAccess;
using USoft.Globalization;

namespace USoft.Modules.IT
{
    public partial class ActivityTaskAddEdit : USoft.Modules.PageBase
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            getUserInfo();
            LoadControl();

            if (!Page.IsPostBack)
            {
                // Binding
                ControlBindingHelper.BindDataSetToCombo(ddlItemType, "- Select One -", "spGetITItemTypeToCombo ''", "ItemTypeCode", "ItemTypeName", null); 
                ControlBindingHelper.BindDataSetToCombo(ddlBranch, "- Select One -", "spGetBranchToCombo ''", "BranchId", "BranchName", null);
                ControlBindingHelper.BindDataSetToCombo(ddlDepartement, "- Select One -", "spGetDepartementToCombo 'DepartementCode NOT IN (''97'',''98'',''99'')'", "DepartementCode", "DepartementName", null);
                ControlBindingHelper.BindDataSetToCombo(ddlProblemType, "- Select One -", "spGetITProblemTypeToCombo ''", "ProblemTypeCode", "ProblemTypeName", null);

                if (this.state == "add")
                {
                    lblActivityNo.Text = "[Generated By System]";
                    txtActivityDate.Text = DateTime.Today.ToString("yyyy-M-d");
                }
                else
                {
                    LoadData();
                }
                FormState();
            }
        }

        private void LoadControl()
        {
            ucHeaderPage.Text = cf.ToUpperFirstLetter(this.state) + " Activity Task";
            ucHeaderPage.CssClass = "divHeader1";
        }

        private void LoadData()
        {
            USoft.DataAccess.Entities.IT.ActivityTask info = new USoft.DataAccess.Entities.IT.ActivityTask();
            USoft.DataAccess.IT.ActivityTask da = new USoft.DataAccess.IT.ActivityTask();

            info.ActivityNo = editID;

            da.getActivityTaskView(ref info);

            lblActivityNo.Text = info.ActivityNo;
            txtActivityDate.Text = cf.DateFormatYYYYMMDD(info.ActivityDate);
            txtRequestBy.Text = info.RequestBy;
            //txtEmail.Text = info.Email;
            ddlBranch.SelectedValue = info.BranchId.ToString();
            ddlDepartement.SelectedValue = (ddlBranch.SelectedValue == "8675") ? info.DepartementCode : "";
            ddlProblemType.SelectedValue = info.ProblemTypeCode.ToString();
            ddlItemType.SelectedValue = (ddlProblemType.SelectedValue == "1") ? info.ItemTypeCode : "";
            //ddlItemType.SelectedValue = info.ItemTypeCode;
            txtDescription.Text = info.Description;
            ddlPriority.SelectedValue = info.Priority;
        }

        protected bool ProcessData(string state)
        {
            //CekSessions.BlockUI(this.Page);
            
            USoft.DataAccess.Entities.IT.ActivityTask info = new USoft.DataAccess.Entities.IT.ActivityTask();
            USoft.DataAccess.IT.ActivityTask da = new USoft.DataAccess.IT.ActivityTask();

            info.ActivityDate = Convert.ToDateTime(txtActivityDate.Text); 
            info.RequestBy = txtRequestBy.Text;
            //info.Email = txtEmail.Text;
            info.BranchId = Convert.ToInt16(ddlBranch.SelectedValue);
            info.DepartementCode = (ddlBranch.SelectedValue == "8675") ? ddlDepartement.SelectedValue : "";
            info.ProblemTypeCode = Convert.ToInt32(ddlProblemType.SelectedValue);
            info.ItemTypeCode = (ddlProblemType.SelectedValue == "1") ? ddlItemType.SelectedValue : "";
            //info.ItemTypeCode = ddlItemType.SelectedValue;
            info.Description = txtDescription.Text;
            info.Priority = ddlPriority.SelectedValue;
            info.InputBy = Session["UserId"].ToString();

            if (state == "U")   // Update
            {
                info.ActivityNo = editID;
                lblMessage.Text = da.ActivityTaskUpdate(info);
            }
            else // Add
            {
                lblMessage.Text = da.ActivityTaskInsert(ref info);
                ReturnID = info.ActivityNo;
            }
            
            if (lblMessage.Text == "Process Success")   // Prevent Multiple Add
            {
                return true;
            }
            return false;

            //ScriptManager.RegisterStartupScript(this, this.GetType(), "tmp", "$.unblockUI();", true);
            //CekSessions.UnBlockUI(this.Page, ScriptManager1);
        }
        
        protected void imbSubmit_Click(object sender, ImageClickEventArgs e)
        {
            if (this.state == "add")
            {
                if (ProcessData("A"))
                {
                    //imbSubmit.Visible = false;
                    Response.Redirect("ActivityTaskDetail.aspx?validate=" + validate(0) + "&editID=" + ReturnID + "&msg=" + lblMessage.Text);
                }
            }
            else
            {
                ProcessData("U");
            }            
        }

        protected void RedirectPage()
        {
            if (from == "detail")
            {
                Response.Redirect("ActivityTaskDetail.aspx?validate=" + validate(0) + "&editID=" + editID);
            }
            else
            {
                Response.Redirect("ActivityTask.aspx?validate=" + validate(0));
            }
        }
        
        protected void imbBack_Click(object sender, ImageClickEventArgs e)
        {
            RedirectPage();
        }

        protected void ddlBranch_SelectedIndexChanged(object sender, EventArgs e)
        {
            FormState();
            pnlDataForm.Update();
        }

        protected void ddlProblemType_SelectedIndexChanged(object sender, EventArgs e)
        {
            FormState();
            pnlDataForm.Update();
        }

        protected void FormState()
        {
            trDepartment.Visible = (ddlBranch.SelectedValue == "8675");
            trItemType.Visible = (ddlProblemType.SelectedValue == "1");
        }
    }
}
