using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

using USoft.Globalization.Classes;
using USoft.Common.CommonFunction;
using USoft.DataAccess;
using USoft.Globalization;

namespace USoft.Modules.GeneralAffair.Purchase
{
    public partial class PurchaseOrderAddEdit : USoft.Modules.PageBase
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            getUserInfo();
            LoadControl();

            if (!IsPostBack)
            {
                // Binding
                ControlBindingHelper.BindDataSetToCombo(ddlSupplier, "- Select One -", "spGetGASupplierRequestToCombo ''", "SupplierCode", "SupplierName", null);
                ControlBindingHelper.BindDataSetToCombo(ddlCurrency, "- Select One -", "spGetCurrencyToCombo ''", "CurrencyCode", "CurrencyCode", null);

                if (this.state == "add")
                {
                    lblOrderID.Text = "[Generated By System]";
                }
                else
                {
                    LoadData();
                }
            }
        }

        private void LoadControl()
        {
            ucHeaderPage.Text = cf.ToUpperFirstLetter(this.state) + " Purchase Order";
            ucHeaderPage.CssClass = "divHeader1";
        }

        private void LoadData()
        {
            USoft.DataAccess.Entities.General_Affair.Purchase info = new USoft.DataAccess.Entities.General_Affair.Purchase();
            USoft.DataAccess.General_Affair.Purchase da = new USoft.DataAccess.General_Affair.Purchase();

            info.OrderId = editID;

            da.getPurchaseOrderView(ref info);

            lblOrderID.Text = info.OrderId;
            txtOrderDate.Text = cf.DateFormatYYYYMMDD(info.OrderDate);
            ddlSupplier.SelectedValue = info.SupplierCode;
            ddlCurrency.SelectedValue = info.CurrencyCode;
            txtPIC.Text = info.PIC;
            txtDeliveryDate.Text = (info.DeliveryDate.Year.ToString() != "1") ? cf.DateFormatYYYYMMDD(info.DeliveryDate) : "";
            txtOfferFrom.Text = info.OfferFrom;
            txtOfferNo.Text = info.OfferNo;
            txtOfferDate.Text = (info.OfferDate.Year.ToString() != "1") ? cf.DateFormatYYYYMMDD(info.OfferDate) : "";
            txtDescription.Text = info.Description;
        }

        protected bool ProcessData(string state)
        {
            USoft.DataAccess.Entities.General_Affair.Purchase info = new USoft.DataAccess.Entities.General_Affair.Purchase();
            USoft.DataAccess.General_Affair.Purchase da = new USoft.DataAccess.General_Affair.Purchase();

            info.OrderDate = Convert.ToDateTime(txtOrderDate.Text);
            info.SupplierCode = ddlSupplier.SelectedValue;
            info.CurrencyCode = ddlCurrency.SelectedValue;
            info.PIC = txtPIC.Text;
            info.DeliveryDate = Convert.ToDateTime((txtDeliveryDate.Text != "") ? txtDeliveryDate.Text : "1753-01-01");
            info.OfferFrom = txtOfferFrom.Text;
            info.OfferNo = txtOfferNo.Text;
            info.OfferDate = Convert.ToDateTime((txtOfferDate.Text != "") ? txtOfferDate.Text : "1753-01-01");
            info.Description = txtDescription.Text;
            info.InputBy = Session["UserId"].ToString();

            if (state == "U")   // Update
            {
                info.OrderId = editID;
                lblMessage.Text = da.PurchaseOrderUpdate(info);
            }
            else // Add
            {
                lblMessage.Text = da.PurchaseOrderInsert(ref info);
                ReturnID = info.OrderId;
            }

            if (lblMessage.Text == "Process Success")   // Prevent Multiple Add
            {
                return true;
            }
            return false;
        }

        protected void imbSubmit_Click(object sender, ImageClickEventArgs e)
        {
            CekSessions.BlockUI(this.Page);

            if (this.state == "add")
            {
                if (ProcessData("A"))
                {
                    //imbSubmit.Visible = false;
                    Response.Redirect("PurchaseOrderDetail.aspx?validate=" + validate(0) + "&editID=" + ReturnID + "&msg=" + lblMessage.Text);
                }
            }
            else
            {
                ProcessData("U");
            }

            CekSessions.UnBlockUI(this.Page, ScriptManager1);
        }

        protected void imbBack_Click(object sender, ImageClickEventArgs e)
        {
            if (from == "detail")
            {
                Response.Redirect("PurchaseOrderDetail.aspx?validate=" + validate(0) + "&editID=" + editID);
            }
            else
            {
                Response.Redirect("PurchaseOrder.aspx?validate=" + validate(0));
            }
        }
    }
}
