using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

using USoft.Globalization.Classes;
using USoft.Common.CommonFunction;
using USoft.DataAccess;
using USoft.Globalization;

namespace USoft.Modules.GeneralAffair.Purchase
{
    public partial class PurchaseRequestAddEdit : USoft.Modules.PageBase
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            getUserInfo();
            LoadControl();
            
            if (!IsPostBack)
            {
                // Binding
                ControlBindingHelper.BindDataSetToCombo(ddlItemCategory, "- Select One -", "spGetGAItemCategoryToCombo ''", "ItemCategoryCode", "ItemCategoryName", null); 
                ControlBindingHelper.BindDataSetToCombo(ddlSupplier, "- Select One -", "spGetGASupplierToCombo ''", "SupplierCode", "SupplierName", null);
                ControlBindingHelper.BindDataSetToCombo(ddlCurrency, "- Select One -", "spGetCurrencyToCombo ''", "CurrencyCode", "CurrencyCode", null);
                
                if (this.state == "add")
                {
                    lblRequestID.Text = "[Generated By System]";
                }
                else
                {
                    LoadData();
                }
            }
        }

        private void LoadControl()
        {
            ucHeaderPage.Text = cf.ToUpperFirstLetter(this.state) + " Purchase Request";
            ucHeaderPage.CssClass = "divHeader1";
        }

        private void LoadData()
        {
            USoft.DataAccess.Entities.General_Affair.Purchase info = new USoft.DataAccess.Entities.General_Affair.Purchase();
            USoft.DataAccess.General_Affair.Purchase da = new USoft.DataAccess.General_Affair.Purchase();

            info.RequestId = editID;

            da.getPurchaseRequestView(ref info);

            lblRequestID.Text = info.RequestId;
            txtRequestDate.Text = cf.DateFormatYYYYMMDD(info.RequestDate);
            if (info.Type == "1") { rblType.Items[0].Selected = true; }
            else if (info.Type == "2") { rblType.Items[1].Selected = true; }
            txtReason.Text = info.Reason;
            ddlSupplier.SelectedValue = info.SupplierCode;
            ddlCurrency.SelectedValue = info.CurrencyCode;
            txtDescription.Text = info.Description;
        }

        protected bool ProcessData(string state)
        {
            USoft.DataAccess.Entities.General_Affair.Purchase info = new USoft.DataAccess.Entities.General_Affair.Purchase();
            USoft.DataAccess.General_Affair.Purchase da = new USoft.DataAccess.General_Affair.Purchase();

            info.RequestDate = Convert.ToDateTime(txtRequestDate.Text);
            info.Type = rblType.SelectedValue;
            info.Reason = txtReason.Text;
            info.SupplierCode = ddlSupplier.SelectedValue;
            info.CurrencyCode = ddlCurrency.SelectedValue;
            info.Description = txtDescription.Text;
            info.InputBy = Session["UserId"].ToString();

            if (state == "U")   // Update
            {
                info.RequestId = editID;
                lblMessage.Text = da.PurchaseRequestUpdate(info);
            }
            else // Add
            {
                lblMessage.Text = da.PurchaseRequestInsert(ref info);
                ReturnID = info.RequestId;
            }
            
            if (lblMessage.Text == "Process Success")   // Prevent Multiple Add
            {
                return true;
            }
            return false;
        }

        protected void imbSubmit_Click(object sender, ImageClickEventArgs e)
        {
            CekSessions.BlockUI(this.Page);

            if (this.state == "add")
            {
                if (ProcessData("A"))
                {
                    //imbSubmit.Visible = false;
                    Response.Redirect("PurchaseRequestDetail.aspx?validate=" + validate(0) + "&editID=" + ReturnID + "&msg=" + lblMessage.Text);
                }
            }
            else
            {
                ProcessData("U");
            }

            CekSessions.UnBlockUI(this.Page, ScriptManager1);
        }

        protected void imbBack_Click(object sender, ImageClickEventArgs e)
        {
            if (from == "detail")
            {
                Response.Redirect("PurchaseRequestDetail.aspx?validate=" + validate(0) + "&editID=" + editID);
            }
            else
            {
                Response.Redirect("PurchaseRequest.aspx?validate=" + validate(0));
            }
        }

        protected void ddlItemCategory_SelectedIndexChanged(object sender, EventArgs e)
        {
            //CekSessions.BlockUI(this.Page);

            //ddlItemGroup.Items.Clear();
            //ddlItemType.Items.Clear();
            //lblMeasurement.Text = "";
            //if (ddlItemCategory.SelectedValue != "")
            //{
            //    ControlBindingHelper.BindDataSetToCombo(ddlItemGroup, "- Select One -", "spGetGAItemGroupToCombo 'ItemCategoryCode = ''" + ddlItemCategory.SelectedValue + "'''", "ItemGroupCode", "ItemGroupName", null);
            //}

            //pnlDataForm.Update();

            //CekSessions.UnBlockUI(this.Page, ScriptManager1);
        }
    }
}
